name: flutter_declarative_syntax
description: Flutter Declarative Syntax is a plugin designed to enhance the development experience by providing a declarative syntax for common Flutter widget modifications. This plugin introduces a set of extension methods on existing Flutter widgets, allowing developers to apply common modifications such as layout adjustments, visual effects, and decorations in a more readable and concise manner. It aims to make Flutter code more expressive and easier to maintain.
version: 0.0.3
homepage: https://github.com/maojiu-bb/flutter_declarative_syntax

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
